### Common Config ###
node-base: &node-base
  steps:
    - checkout
    - run:
        name: Update npm
        command: 'npm install -g npm@latest'

    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}

    - run:
        name: Install dependencies
        command: npm install

    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules

    - run:
        name: Test
        command: npm test
### end common config ###

## CircleCI Settings
version: 2
jobs:
  node-lambda:
    <<: *node-base
    docker:
      - image: nousdefions/circleci-lambda:latest
        environment:
          LOCAL_DYNAMO: true
          LOCAL_DYNAMO_PORT: 8000
      - image: amazon/dynamodb-local
  node-v10:
    <<: *node-base
    docker:
      - image: node:10
        environment:
          LOCAL_DYNAMO: true
          LOCAL_DYNAMO_PORT: 8000
      - image: amazon/dynamodb-local

workflows:
  version: 2
  build:
    jobs:
      - node-lambda
      - node-v10
